config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
   }
  devise_for :students, controllers: {
    sessions:      'students/sessions',
    passwords:     'students/passwords',
    registrations: 'students/registrations'
  }
  devise_for :teachers, controllers: {
    sessions:      'teachers/sessions',
    passwords:     'teachers/passwords',
    registrations: 'teachers/registrations'
  }

  root 'static_pages#home'
  resources :grades
  resources :groups
end

app/models/grade.rb
class Grade < ApplicationRecord
  has_many :groups

  validates :grade_number, presence: true, uniqueness: { case_sensitive: true },
                           numericality: { :greater_than_or_equal_to => 1, less_than_or_equal_to: 99}
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @grades = Grade.all
  end

  def show
  end

  def new
    @grade = Grade.new
  end

  def create
    @grade = Grade.new(grade_params)
    @grade.save

    if @grade.save
      flash[:success] = '学年が作成されました。'
      redirect_to grades_path
    else
      render 'grades/new'
    end
  end

  def edit
  end

  def destroy
  end

  private

  def grade_params
    params.require(:grade).permit(:grade_number)
  end
end

app/views/grades/_form.html.erb
<%= form_with(model: Grade.new, local: true) do |form| %>
  <div>
    <%= form.hidden_field :grade_number %>
    <%= form.text_field :grade_number, placeholder: "学年番号" %>
  </div>

  <div>
    <%= form.submit "登録" %>
  </div>
<% end %>

app/views/grades/edit.html.erb
<h1>Grade#edit</h1>
<p>Find me in app/views/grade/edit.html.erb</p>

app/views/grades/index.html.erb
<h1>学年一覧</h1>

<% if admin_signed_in? %>
  <%= link_to new_grade_path do %>
    <div>学年作成</div>
  <% end %>
<% end %>

<% @grades.each do |grade| %>
  <div>
    <div>
      <%= link_to "#{grade.grade_number}学年", group_path(grade) %>
    </div>
  </div>
<% end %>

app/views/grades/new.html.erb
<h2>学年の作成</h2>

<%= render 'form' %>

app/views/grades/show.html.erb
<h1>Grade#show</h1>
<p>Find me in app/views/grade/show.html.erb</p>