config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
   }
  devise_for :students, controllers: {
    sessions:      'students/sessions',
    passwords:     'students/passwords',
    registrations: 'students/registrations'
  }
  devise_for :teachers, controllers: {
    sessions:      'teachers/sessions',
    passwords:     'teachers/passwords',
    registrations: 'teachers/registrations'
  }

  root 'static_pages#home'
  resources :grades
  resources :groups
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :grade

  validates :grade_id, presence: true
  VALID_GROUP_NUMBER_REGEX = /[0-9]+/.freeze
  validates :group_number, presence: true, length: { in: 1..20 }, format: { with: VALID_GROUP_NUMBER_REGEX }
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_admin!

  def index
  end

  def show
    @grade = Grade.find(params[:id])
    @groups = Group.where("grade_id = '#{@grade.id}'")
  end

  def new
    @group = Group.new
    @grade = Grade.find(params[:grade_id])
  end

  def create
    @group = Group.new(group_params)
    @group.grade_id = params[:grade_id] unless params[:grade_id].blank?
    @group.save

    if @group.save
      flash[:success] = 'クラスが作成されました。'
      redirect_to group_path(@group.grade_id)
    else
      render 'groups/new'
    end
  end

  def edit
  end

  def destroy
  end

  private

  def group_params
    params.require(:group).permit(:group_number, :grade_id)
  end
end

app/views/groups/_form.html.erb
<%= form_with(model: Group.new, local: true) do |form| %>
  <div>
    <%= form.hidden_field :grade_id, { value: @grade.id } %>
  </div>

  <div>
    <%= form.hidden_field :group_number %>
    <%= form.text_field :group_number, placeholder: "クラス番号" %>
  </div>

  <div>
    <%= form.submit "登録" %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Group#edit</h1>
<p>Find me in app/views/group/edit.html.erb</p>

app/views/groups/new.html.erb
<h2><%= @grade.grade_number %>学年のクラス作成</h2>

<%= render 'form', grade: @grade %>

app/views/groups/show.html.erb
<h2>
  <%= @grade.grade_number %>学年
</h2>

<% if admin_signed_in? %>
  <%= link_to new_group_path(grade_id: @grade.id) do %>
    <div>クラス作成</div>
  <% end %>
<% end %>

<% @groups.each do |group| %>
  <div>
    <div>
      <%= link_to "#{group.group_number}クラス" %>
    </div>
  </div>
<% end %>