config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
   }
  devise_for :students, controllers: {
    sessions:      'students/sessions',
    passwords:     'students/passwords',
    registrations: 'students/registrations'
  }
  devise_for :teachers, controllers: {
    sessions:      'teachers/sessions',
    passwords:     'teachers/passwords',
    registrations: 'teachers/registrations'
  }

  root 'static_pages#home'
  resources :grades
  resources :groups
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="notice-cover">
    <%= content_tag(:div, value, class: "#{key}") %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header class="header">
  <h1 class="header-logo">
    <%= link_to website_name, root_path %>
  </h1>
  <nav class="nav-cover">
    <ul class="nav">
      <% if admin_signed_in? %>
        <li class="nav-item">
          <%= link_to "学年一覧", grades_path %>
        </li>
        <li class="nav-item">
          <%= button_to "ログアウト", destroy_admin_session_path, method: :delete %>
        </li>
      <% elsif teacher_signed_in? %>
      <% elsif student_signed_in? %>
      <% else %>
        <li class="nav-item">
          <%= link_to "管理者はこちら", new_admin_session_path %>
        </li>
        <li class="nav-item">
          <%= link_to "先生はこちら", new_teacher_session_path %>
        </li>
        <li class="nav-item">
          <%= link_to "生徒はこちら", new_student_session_path %>
        </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GradeManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="content-language" content="ja" charset="utf-8">
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <%= render 'layouts/flash_messages' %>

      <% unless current_page?(root_path) %>
        <main>
          <%= yield %>
        </main>
      <% else %>
        <main>
          <%= yield %>
        </main>
      <% end %>
    </div>
  </body>
</html>